export const ERROR_CODES = {
  AL_ERROR: 'ANILIST_ERROR',
  MAL_ERROR: 'MAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  NO_REFRESH_TOKEN: 'NO_REFRESH_TOKEN',
  NO_PROVIDER_FOUND: 'NO_PROVIDER_FOUND',
  ACCESS_TOKEN_EXPIRED: 'ACCESS_TOKEN_EXPIRED',
};
