'use client';

import './globals.css';

import { Geist, Geist_Mono as GeistMono } from 'next/font/google';
import { ReactQueryClientProvider } from '@/providers/react-query-client-provider';
import { ColorModeScript, UIProvider } from '@yamada-ui/react';
import { useEffect } from 'react';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = GeistMono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

/**
 * Root Layout Component
 * @param {{children: import("react").ReactNode}} root0
 * @param {import("react").ReactNode} root0.children
 * @returns {import("react").ReactNode}
 */
export default function RootLayout({ children }) {
  useEffect(() => {
    window.__APP_CONTEXT_READY__ = true;
  }, []);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryClientProvider>
          <ColorModeScript />
          <UIProvider>{children}</UIProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
